### ISSUE TITLE
Exact structure searches

### ISSUE THREAD

**Issue by paconius** [rdkit/django-rdkit#14]
I note that rdkit-django performs two substructure searches instead of an equals search when implementing the django "exact" operator.  For the sake of overall performance it would seem to be beneficial to perform a simple exact query rather than two substructure queries. Looking at the code, the exact search appears to be commented out of the function SameStructure [models.py -- snip below] and replaced with the two substructure alternative. Any rememberances as to why this is implemented this way?

```
class SameStructure(Lookup):
...
#return '%s @= %s' % (lhs, rhs), params
return '%s <@ %s AND %s @> %s' % (lhs, rhs, lhs, rhs), params + params
```

**Comment by rvianello** [comment]
Hi @paconius 

great question, I don't remember exactly, but I think at the time of the first productive release of this library, there was a bug in the cartridge code affecting the `@=` operator.

One reason why this issue wasn't considered very critical is that same-structure queries are often more efficient when simply based on the comparison of a canonical smiles string, but if `@=` can be now confirmed to work reliably, I would be fine with restoring the commented-out version. I'll try and find some time to review the details.

Best,
Riccardo

**Comment by paconius** [comment]
Thanks for the info Riccardo. Your comment about cannonical smiles being the best (fastest?) way to do exact matching is an interesting one. Is this how you personally perform exact searches?

If this has merit, then perhaps best practice would be to always have an indexed canonical smiles string field that is populated for every structure and then use the database string operators to perform exact searches. If this is true then it might make sense to promote this an an improvement to the cartridge code. Greg has several blog posts on the sped of the cartridge, so I imagine he would be interested in your solution if it is fastest.

**Comment by rvianello** [comment]
Hi @paconius 

I think this is the issue I recalled https://github.com/rdkit/rdkit/issues/525 - it was actually fixed ages ago, so restoring the commented out version of the exact lookup - as you initially suggested - would definitely make sense.

Interestingly, the implementation of the mol comparison operators I think performs a both-ways substructure test, before resorting to a canonical smiles comparison:
https://github.com/rdkit/rdkit/blob/master/Code/PgSQL/rdkit/adapter.cpp#L424

Anyways, yes, when exact lookup operations are to be performed on a more than occasional basis, I prefer to use a dedicated indexed column filled with the canonical smiles (not my invention, and to be honest, I never performed a dedicated benchmark, I would be just very surprised if it wasn't quite faster). I am not sure I would automate this pattern on every mol column though, because requirements vary, and I'm not sure it would represent a very valuable addition for the cartridge considering that the necessary functionalities are already easily available (but this is just my personal feeling).

Best,
Riccardo
